spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect