spring:
  datasource:
    url: jdbc:mysql://localhost/api_delivery?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true